#!/usr/bin/env python3
"""Run the real-model search-quality suite and write RESULTS.md (#559 PR2b).

The dogfooding artifact runner: it drives the SAME engine the pytest classes
assert against (``tests.search_quality.runner.run_search_quality``) — one source
of truth — and renders the per-class recall/precision numbers, the cross-space
floor-admission behaviour (#580), and the cross-lingual observations to
``eval/search_quality/RESULTS.md`` (gitignored — a local artifact).

It is the manual suite's reporting half: where the pytest classes assert floors,
this prints the actual numbers so a human (or #580's margin tuning) can read where
the real models land. Same off-CI posture — it needs the cached models + the Commons
corpus, runs nothing in CI.

Run::

    python scripts/eval_search_quality.py            # build, run, write RESULTS.md
    python scripts/eval_search_quality.py --print     # also echo the report to stdout
"""

from __future__ import annotations

import argparse
import asyncio
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

RESULTS = ROOT / "eval" / "search_quality" / "RESULTS.md"


def _fmt(x: float | None) -> str:
    return "n/a" if x is None else f"{x:.3f}"


def _render(result, elapsed: float) -> str:
    from tests.search_quality.metrics import FailureKind
    from tests.search_quality.runner import clip_fired

    suite = result.suite
    lines: list[str] = [
        "# Search-quality eval results (#559)",
        "",
        "Real-model adversarial recall + precision over the Wikimedia Commons",
        "corpus (a dedicated MiniLM text space + a separate CLIP image space, the",
        "#229/#232/#234 multi-space loop), driven through the REAL `search_notes`",
        "MCP action. Generated by `scripts/eval_search_quality.py` — the same",
        "engine the `tests/integration/test_search_quality.py` classes assert.",
        "",
        f"- spaces attached: **{result.space_count}** (text + CLIP)",
        f"- index vectors: **{result.index_size}** (text + image)",
        f"- queries: **{len(suite.queries)}**",
        f"- run time: **{elapsed:.1f}s** (warm cache)",
        "",
        "Grades: 0 = planted distractor, 1 = marginal, 2 = relevant, 3 = canonical.",
        "Recall denominator = grade>=2; open-world (per-query sparse gold), so FPR",
        "counts only the explicit grade-0 hard-negatives.",
        "",
        "## Recall + precision by adversarial class",
        "",
        "| Class | n | R@1 | R@5 | R@k | MRR | nDCG@10 | mean FPR |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]

    # group reports by class for the per-class FPR mean
    by_class: dict[str, list] = {}
    for q in suite.queries:
        by_class.setdefault(q.adversarial_class, []).append(q)
    for cls in suite.classes():
        qs = by_class[cls]
        fprs = [q.false_positive_rate for q in qs if q.false_positive_rate is not None]
        mean_fpr = sum(fprs) / len(fprs) if fprs else None
        lines.append(
            f"| {cls} | {len(qs)} | "
            f"{_fmt(suite.mean_recall_at_1(by_class=cls))} | "
            f"{_fmt(suite.mean_recall_at_5(by_class=cls))} | "
            f"{_fmt(suite.mean_recall_at_k(by_class=cls))} | "
            f"{_fmt(suite.mean_mrr(by_class=cls))} | "
            f"{_fmt(suite.mean_ndcg(by_class=cls))} | "
            f"{_fmt(mean_fpr)} |"
        )

    lines += [
        "",
        f"**Overall**: R@k = {_fmt(suite.mean_recall_at_k())}, "
        f"MRR = {_fmt(suite.mean_mrr())}, nDCG@10 = {_fmt(suite.mean_ndcg())}.",
        "",
        "## Cross-space floor-admission (#580)",
        "",
        "The `image#clip` signal contributes whenever the CLIP image space clears",
        "its own calibrated floor for the query (floor-admission, #580 — the",
        "relative winner-take-all gate is retired). So a card's image corroborates",
        "it even when the text/filename also won. `top-1` shows the text answer",
        "still wins for the gate-no-inject fact queries.",
        "",
        "| Query | image#clip contributes | top-1 |",
        "| --- | --- | --- |",
    ]
    for q in result.manifest.queries:
        if q.adversarial_class not in (
            "modality_gap",
            "gate_no_inject_portrait",
            "spurious_filename",
        ):
            continue
        ms = result.returns.get(q.q, [])
        fired = any(clip_fired(m) for m in ms)
        top1 = ms[0]["id"] if ms else "—"
        lines.append(f"| {q.q[:54]} | {'yes' if fired else 'no'} | {top1} |")

    lines += [
        "",
        "## Cross-lingual observations (characterized, not floored)",
        "",
        "Exact-match and image paths work regardless of model language; semantic",
        "cross-lingual recall depends on the English-centric MiniLM/CLIP, so it is",
        "documented here rather than asserted.",
        "",
    ]
    for q in result.manifest.queries:
        if "lingual" not in q.adversarial_class:
            continue
        report = next(r for r in suite.queries if r.query == q.q)
        lines.append(
            f"- `{q.q}` ({q.adversarial_class}): R@1={_fmt(report.recall_at_1)}, "
            f"R@k={_fmt(report.recall_at_k)} — expected signal `{q.expected_signal}`"
        )

    # failure rollup
    rolled = suite.failures_by_kind()
    lines += ["", "## Tagged divergences", ""]
    any_fail = False
    for kind in FailureKind:
        fs = rolled[kind]
        if fs:
            any_fail = True
            lines.append(f"- **{kind.value}**: {len(fs)}")
    if not any_fail:
        lines.append("None.")
    lines.append("")
    return "\n".join(lines)


async def _run():
    from tests.search_quality.runner import run_search_quality

    t0 = time.time()
    with tempfile.TemporaryDirectory() as tmp:
        result = await run_search_quality(Path(tmp))
    return result, time.time() - t0


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--print", action="store_true", help="echo the report to stdout too")
    args = ap.parse_args()

    print("Running the real-model search-quality suite (downloads images + models on first run)...")
    result, elapsed = asyncio.run(_run())
    report = _render(result, elapsed)
    RESULTS.parent.mkdir(parents=True, exist_ok=True)
    RESULTS.write_text(report)
    print(
        f"\nwrote {RESULTS.relative_to(ROOT)} ({len(result.suite.queries)} queries, {elapsed:.1f}s)"
    )
    if args.print:
        print("\n" + report)


if __name__ == "__main__":
    main()
