"""Type stubs for the compiled shrike_native._native module (#269).

Hand-written against native/shrike-py/src/lib.rs; mypy.stubtest in the native
CI lane fails if a Rust signature drifts from these.
"""

from asyncio import Future

from collections.abc import Callable
from typing import final

# pyo3's #[pymodule] auto-generates __all__ from the registered names.
__all__ = [
    "version",
    "build_info",
    "parallel_sum",
    "checked_div",
    "init_logging",
    "init_onnx_runtime",
    "rrf_fuse",
    "schema_catalog",
    "schema_roundtrip",
    "fused_search_text",
    "fused_add_text",
    "derived_fts5_probe",
    "derived_sqlite_bundled",
    "OnnxTextEmbedder",
    "ClipEmbedder",
    "NativeIndexEngine",
    "DerivedTextEngine",
    "IMAGE_PREP_VERSION_RS",
    "NativeInputError",
    "NativeUnavailableError",
    "NativeInternalError",
    "NativeBusyError",
]

class NativeInputError(ValueError): ...
class NativeUnavailableError(RuntimeError): ...
class NativeInternalError(RuntimeError): ...
class NativeBusyError(RuntimeError): ...

IMAGE_PREP_VERSION_RS: int

def version() -> str: ...
def build_info() -> str: ...
def parallel_sum(values: list[float]) -> float: ...
def checked_div(a: float, b: float) -> float: ...
def init_logging() -> None: ...
def fetch_media_url(url: str, allow_private: bool = False) -> tuple[bytes, str | None]: ...
def decode_media_b64(data: str) -> bytes: ...
def rehomed_actions() -> list[str]: ...
def action_collection_info(
    core: CollectionCore, include: list[str], note_type_details: list[str]
) -> str: ...
def action_list_notes(
    core: CollectionCore,
    ids: list[int] | None = None,
    deck: str | None = None,
    tags: list[str] | None = None,
    note_type: str | None = None,
    modified_since_epoch: int | None = None,
    with_fields: bool = True,
    limit: int = 50,
) -> str: ...
def action_collection_query(
    core: CollectionCore, query: str, with_fields: bool = True, limit: int = 50
) -> str: ...
def action_search_notes(
    core: CollectionCore,
    index_engine: NativeIndexEngine | None,
    derived_engine: DerivedTextEngine | None,
    sources: list[tuple[str, str, bool]],
    vectors: list[list[float]],
    top_k: int,
    threshold: float,
    deck: str | None = None,
    tags: list[str] | None = None,
    exclude: list[int] | None = None,
    image_floor: float | None = None,
    weights: dict[str, float] | None = None,
    semantic: bool = False,
    index_size: int = 0,
) -> str: ...
def init_onnx_runtime(dylib_path: str) -> None: ...
def derived_fts5_probe() -> bool: ...
def derived_sqlite_bundled() -> bool: ...
def schema_catalog() -> dict[str, str]: ...
def schema_roundtrip(name: str, json: str) -> str: ...
def rrf_fuse(
    rankings: list[tuple[str, list[int]]],
    weights: dict[str, float],
    k: int = 60,
    priority_signals: list[str] = ...,
) -> list[tuple[int, float, list[tuple[str, int]]]]: ...
def fused_search_text(
    embedder: OnnxTextEmbedder,
    engine: NativeIndexEngine,
    texts: list[str],
    k: int,
    modalities: list[str] | None = None,
) -> list[dict[str, tuple[list[int], list[float]]]]: ...
def fused_add_text(
    embedder: OnnxTextEmbedder,
    engine: NativeIndexEngine,
    modality: str,
    keys: list[int],
    texts: list[str],
    chunk: int,
) -> int: ...

@final
class OnnxTextEmbedder:
    def __new__(
        cls,
        model_path: str,
        tokenizer_path: str,
        *,
        providers: list[str],
        pooling: str,
        normalize: bool,
        max_length: int,
    ) -> OnnxTextEmbedder: ...
    def embed_chunk(self, texts: list[str]) -> list[list[float]]: ...
    def dim(self) -> int | None: ...
    def active_providers(self) -> list[str]: ...
    def unsupported_inputs(self) -> list[str]: ...

@final
class ClipEmbedder:
    def __new__(
        cls,
        text_model_path: str,
        vision_model_path: str,
        tokenizer_path: str,
        *,
        providers: list[str],
        image_mean: list[float],
        image_std: list[float],
        resize: int,
        crop: int,
        context: int,
    ) -> ClipEmbedder: ...
    def embed_text_chunk(self, texts: list[str]) -> list[list[float]]: ...
    def embed_image_chunk(self, images: list[bytes]) -> list[list[float]]: ...
    def dim(self) -> int | None: ...
    def active_providers(self) -> list[str]: ...

@final
class NativeIndexEngine:
    def __new__(cls, modalities: list[str]) -> NativeIndexEngine: ...
    def size(self) -> int: ...
    def ndim(self) -> int | None: ...
    def modality_sizes(self) -> list[tuple[str, int]]: ...
    def modality_names(self) -> list[str]: ...
    def ensure(self, modality: str, ndim: int) -> None: ...
    def clear(self) -> None: ...
    def drop_modality(self, modality: str) -> None: ...
    def restore(self, path: str, candidate_keys: list[int] | None = None) -> bool: ...
    def save(self, path: str) -> None: ...
    def add(self, modality: str, keys: list[int], vectors: list[list[float]]) -> None: ...
    def remove(self, keys: list[int]) -> int: ...
    def search_by_modality(
        self,
        queries: list[list[float]],
        k: int,
        modalities: list[str] | None = None,
    ) -> list[dict[str, tuple[list[int], list[float]]]]: ...
    def contains(self, key: int) -> bool: ...
    def keys(self) -> list[int]: ...
    def get(self, key: int) -> list[list[float]] | None: ...
    def modality_contains(self, modality: str, key: int) -> bool: ...
    def modality_keys(self, modality: str) -> list[int]: ...
    def modality_get(self, modality: str, key: int) -> list[list[float]] | None: ...
    def calibrate_activation(
        self, sample_size: int, k: int, min_count: int
    ) -> list[tuple[str, float, float, float]]: ...

# Feature-gated (#278): exists only in `anki-core` builds. Absent from default
# builds — listed in stubtest_allowlist.txt so the default-build stubtest run
# tolerates the stub-only name (and --ignore-unused-allowlist tolerates the
# entry on a feature build). Kept OUT of __all__ (the default-build surface).
@final
class WorkerExecutor:
    def __new__(cls) -> WorkerExecutor: ...
    def worker_loop(self) -> None: ...
    def shutdown(self) -> None: ...

@final
class LoopTimerHost:
    @staticmethod
    def capture() -> LoopTimerHost: ...

def timer_probe(
    host: LoopTimerHost, delay_secs: float, cancel_after: float | None = None
) -> Future[bool]: ...

@final
class PyEmbedder:
    @staticmethod
    def capture(backend: object) -> PyEmbedder: ...

def embedder_probe(embedder: PyEmbedder, texts: list[str]) -> Future[list[list[float]]]: ...
@final
class KernelIndex:
    def __new__(cls, dir: str, engine: NativeIndexEngine) -> KernelIndex: ...
    def state(self) -> str: ...
    def build_progress(self) -> tuple[int, int]: ...
    def col_mod(self) -> int | None: ...
    def set_col_mod(self, value: int) -> None: ...
    def model_id(self) -> str | None: ...
    def has_note_hashes(self) -> bool: ...
    def check_drift(
        self,
        current_col_mod: int,
        current_model_id: str | None = None,
        embeds_images: bool = False,
    ) -> bool: ...
    def remove(self, note_ids: list[int]) -> int: ...
    def materialize_empty(
        self, ndim: int, col_mod: int, model_id: str | None = None
    ) -> None: ...
    def save(self) -> None: ...
    def calibrate_activation(self) -> None: ...
    def status_json(self) -> str: ...
    def add(
        self, inputs: list[tuple[int, str, list[str]]], embedder: PyEmbedder
    ) -> Future[int]: ...
    def rebuild(
        self,
        inputs: list[tuple[int, str, list[str]]],
        col_mod: int,
        model_id: str | None,
        embedder: PyEmbedder,
    ) -> Future[None]: ...
    def reconcile(
        self,
        inputs: list[tuple[int, str, list[str]]],
        col_mod: int,
        model_id: str | None,
        embedder: PyEmbedder,
    ) -> Future[None]: ...

@final
class KernelIndexSaver:
    def __new__(
        cls, index: KernelIndex, timers: LoopTimerHost, delay: float, threshold: int
    ) -> KernelIndexSaver: ...
    def request_save(self) -> None: ...
    def pending_changes(self) -> int: ...
    def flush(self) -> None: ...

@final
class AsyncCollection:
    def col_mod(self) -> Future[int]: ...
    def find_notes(self, query: str) -> Future[list[int]]: ...
    def close(self) -> Future[None]: ...

def async_collection_open(
    collection_path: str, executor: WorkerExecutor | None = None
) -> Future[AsyncCollection]: ...
@final
class AsyncKernel:
    def upsert_notes(
        self,
        notes: list[tuple[int, int, list[str], list[str]]],
        on_duplicate: str,
    ) -> Future[list[tuple[str, int | None, str | None]]]: ...
    def delete_notes(self, note_ids: list[int]) -> Future[int]: ...
    def search(
        self, query: str, top_k: int
    ) -> Future[list[tuple[int, float, list[tuple[str, int]]]]]: ...
    def reindex_if_needed(self) -> Future[bool]: ...
    def col_mod(self) -> Future[int]: ...
    def index_status_json(self) -> str: ...
    def save_index(self) -> None: ...
    def run_job(self, job: Callable[[], object]) -> Future[object]: ...
    def engine_handle(self) -> NativeIndexEngine: ...
    def core_handle(self) -> CollectionCore: ...
    def release(self) -> Future[None]: ...
    def reopen(self) -> Future[None]: ...
    def close(self) -> Future[None]: ...

def async_kernel_open(
    collection_path: str,
    cache_dir: str,
    embedder: PyEmbedder,
    executor: WorkerExecutor | None = None,
    media_read: Callable[[str], bytes | None] | None = None,
    media_exists: Callable[[str], bool] | None = None,
) -> Future[AsyncKernel]: ...

class CollectionCore:
    def __new__(cls, collection_path: str) -> CollectionCore: ...
    def close(self) -> None: ...
    def release(self) -> None: ...
    def reopen(self) -> None: ...
    def col_mod(self) -> int: ...
    def find_notes(self, search: str) -> list[int]: ...
    def notetype_id(self, name: str) -> int: ...
    def get_note(self, note_id: int) -> tuple[int, int, list[str], list[str]]: ...
    def create_note(
        self,
        notetype_id: int,
        deck_id: int,
        fields: list[str],
        tags: list[str],
        on_duplicate: str = "error",
    ) -> int | None: ...
    def update_note(
        self, note_id: int, fields: list[str], tags: list[str] | None = None
    ) -> None: ...
    def delete_notes(self, note_ids: list[int]) -> int: ...
    def cards_of_note(self, note_id: int) -> list[int]: ...
    def card_ords_of_note(self, note_id: int) -> list[tuple[int, int]]: ...
    def upsert_notes(
        self, notes_json: str, on_duplicate: str = "error", dry_run: bool = False
    ) -> str: ...
    def update_note_tags(
        self,
        note_ids: list[int],
        set_tags: list[str] | None = None,
        add: list[str] | None = None,
        remove: list[str] | None = None,
    ) -> tuple[int, list[int]]: ...
    def rename_tag(self, old: str, new: str, note_ids: list[int]) -> int: ...
    def upsert_decks(self, decks_json: str) -> str: ...
    def delete_decks(self, refs: list[str]) -> str: ...
    def find_replace_notes(
        self,
        note_ids: list[int],
        search: str,
        replacement: str,
        regex: bool = False,
        match_case: bool = True,
        field: str | None = None,
    ) -> str: ...
    def delete_note_types(self, ids: list[int]) -> str: ...
    def store_media_bytes(
        self, data: bytes, filename: str | None = None, content_type: str | None = None
    ) -> str: ...
    def store_media_items(
        self,
        items_json: str,
        allow_private_fetch: bool = False,
        path_roots: list[str] | None = None,
    ) -> str: ...
    def media_ip_allowed(self, ip: str) -> bool: ...
    def fetch_media(self, filenames: list[str]) -> str: ...
    def list_media(self, pattern: str | None = None, limit: int | None = None) -> str: ...
    def delete_media(self, filenames: list[str]) -> str: ...
    def media_check(self) -> str: ...
    def prune(
        self,
        unused_tags: bool = True,
        empty_notes: bool = True,
        empty_cards: bool = True,
        unused_media: bool = True,
        dry_run: bool = True,
    ) -> str: ...
    def upsert_note_types(self, note_types_json: str) -> str: ...
    def update_note_type_fields(self, note_type_name: str, operations_json: str) -> str: ...
    def update_note_type_templates(self, note_type_name: str, operations_json: str) -> str: ...
    def find_replace_note_types(
        self,
        note_type_name: str,
        search: str,
        replacement: str,
        regex: bool = False,
        match_case: bool = True,
        front: bool = True,
        back: bool = True,
        css: bool = True,
    ) -> str: ...
    def update_note_type_field_metadata(self, note_type_name: str, updates_json: str) -> str: ...
    def migrate_note_type(
        self,
        note_ids: list[int],
        new_note_type: str,
        field_map_json: str,
        template_map_json: str = "",
        dry_run: bool = False,
    ) -> str: ...
    def note_texts(self, note_ids: list[int]) -> list[str]: ...
    def note_embed_inputs(self, note_ids: list[int]) -> list[tuple[int, str, list[str]]]: ...
    def derived_field_rows(self, note_ids: list[int]) -> list[tuple[int, str, str, str]]: ...
    def normalize_text(self, value: str) -> str: ...
    def query(self, search: str, with_fields: bool = True, limit: int = 50) -> str: ...
    def note_field_map(self, note_ids: list[int]) -> list[tuple[int, list[str], list[str]]]: ...
    def resolve_deck_ref(self, reference: str) -> str | None: ...
    def list_notes(
        self,
        ids: list[int] | None = None,
        deck: str | None = None,
        tags: list[str] | None = None,
        note_type: str | None = None,
        modified_since: int | None = None,
        with_fields: bool = True,
        limit: int = 50,
    ) -> str: ...
    def collection_info(
        self,
        sections: list[str] | None = None,
        detail_names: list[str] | None = None,
    ) -> str: ...

@final
class DerivedTextEngine:
    def __new__(cls, path: str, schema_version: int) -> DerivedTextEngine: ...
    def close(self) -> None: ...
    def get_col_mod(self) -> int | None: ...
    def set_col_mod(self, value: int) -> None: ...
    def count(self) -> int: ...
    def ingest(self, note_id: int, source: str, refs_text: list[tuple[str, str]]) -> None: ...
    def remove(self, note_ids: list[int], source: str | None = None) -> None: ...
    def build(self, rows: list[tuple[int, str, str, str]], col_mod: int) -> None: ...
    def match_rows(
        self, expr: str, limit: int, with_text: bool
    ) -> list[tuple[int, str, str, str | None, str | None]]: ...
    def search_substring(
        self, query: str, limit: int
    ) -> list[tuple[int, str, str, str | None]] | None: ...
    def search_fuzzy(self, query: str, top_k: int) -> list[tuple[int, str, str, str | None]]: ...
