"""Type stubs for the compiled shrike_native._native module (#269).

Hand-written against native/shrike-py/src/lib.rs; mypy.stubtest in the native
CI lane fails if a Rust signature drifts from these.
"""

from typing import final

# pyo3's #[pymodule] auto-generates __all__ from the registered names.
__all__ = [
    "version",
    "build_info",
    "parallel_sum",
    "checked_div",
    "init_logging",
    "init_onnx_runtime",
    "rrf_fuse",
    "fused_search_text",
    "fused_add_text",
    "derived_fts5_probe",
    "derived_sqlite_bundled",
    "OnnxTextEmbedder",
    "ClipEmbedder",
    "NativeIndexEngine",
    "DerivedTextEngine",
    "IMAGE_PREP_VERSION_RS",
    "NativeInputError",
    "NativeUnavailableError",
    "NativeInternalError",
]

class NativeInputError(ValueError): ...
class NativeUnavailableError(RuntimeError): ...
class NativeInternalError(RuntimeError): ...

IMAGE_PREP_VERSION_RS: int

def version() -> str: ...
def build_info() -> str: ...
def parallel_sum(values: list[float]) -> float: ...
def checked_div(a: float, b: float) -> float: ...
def init_logging() -> None: ...
def init_onnx_runtime(dylib_path: str) -> None: ...
def derived_fts5_probe() -> bool: ...
def derived_sqlite_bundled() -> bool: ...
def rrf_fuse(
    rankings: list[tuple[str, list[int]]],
    weights: dict[str, float],
    k: int = 60,
    priority_signals: list[str] = ...,
) -> list[tuple[int, float, list[tuple[str, int]]]]: ...
def fused_search_text(
    embedder: OnnxTextEmbedder,
    engine: NativeIndexEngine,
    texts: list[str],
    k: int,
    modalities: list[str] | None = None,
) -> list[dict[str, tuple[list[int], list[float]]]]: ...
def fused_add_text(
    embedder: OnnxTextEmbedder,
    engine: NativeIndexEngine,
    modality: str,
    keys: list[int],
    texts: list[str],
    chunk: int,
) -> int: ...

@final
class OnnxTextEmbedder:
    def __new__(
        cls,
        model_path: str,
        tokenizer_path: str,
        *,
        providers: list[str],
        pooling: str,
        normalize: bool,
        max_length: int,
    ) -> OnnxTextEmbedder: ...
    def embed_chunk(self, texts: list[str]) -> list[list[float]]: ...
    def dim(self) -> int | None: ...
    def active_providers(self) -> list[str]: ...
    def unsupported_inputs(self) -> list[str]: ...

@final
class ClipEmbedder:
    def __new__(
        cls,
        text_model_path: str,
        vision_model_path: str,
        tokenizer_path: str,
        *,
        providers: list[str],
        image_mean: list[float],
        image_std: list[float],
        resize: int,
        crop: int,
        context: int,
    ) -> ClipEmbedder: ...
    def embed_text_chunk(self, texts: list[str]) -> list[list[float]]: ...
    def embed_image_chunk(self, images: list[bytes]) -> list[list[float]]: ...
    def dim(self) -> int | None: ...
    def active_providers(self) -> list[str]: ...

@final
class NativeIndexEngine:
    def __new__(cls, modalities: list[str]) -> NativeIndexEngine: ...
    def size(self) -> int: ...
    def ndim(self) -> int | None: ...
    def modality_sizes(self) -> list[tuple[str, int]]: ...
    def modality_names(self) -> list[str]: ...
    def ensure(self, modality: str, ndim: int) -> None: ...
    def clear(self) -> None: ...
    def drop_modality(self, modality: str) -> None: ...
    def restore(self, path: str, candidate_keys: list[int] | None = None) -> bool: ...
    def save(self, path: str) -> None: ...
    def add(self, modality: str, keys: list[int], vectors: list[list[float]]) -> None: ...
    def remove(self, keys: list[int]) -> int: ...
    def search_by_modality(
        self,
        queries: list[list[float]],
        k: int,
        modalities: list[str] | None = None,
    ) -> list[dict[str, tuple[list[int], list[float]]]]: ...
    def contains(self, key: int) -> bool: ...
    def keys(self) -> list[int]: ...
    def get(self, key: int) -> list[list[float]] | None: ...
    def modality_contains(self, modality: str, key: int) -> bool: ...
    def modality_keys(self, modality: str) -> list[int]: ...
    def modality_get(self, modality: str, key: int) -> list[list[float]] | None: ...
    def calibrate_activation(
        self, sample_size: int, k: int, min_count: int
    ) -> list[tuple[str, float, float, float]]: ...

# Feature-gated (#278): exists only in `anki-core` builds. Absent from default
# builds — listed in stubtest_allowlist.txt so the default-build stubtest run
# tolerates the stub-only name (and --ignore-unused-allowlist tolerates the
# entry on a feature build). Kept OUT of __all__ (the default-build surface).
@final
class CollectionCore:
    def __new__(cls, collection_path: str) -> CollectionCore: ...
    def close(self) -> None: ...
    def col_mod(self) -> int: ...
    def find_notes(self, search: str) -> list[int]: ...
    def notetype_id(self, name: str) -> int: ...
    def get_note(self, note_id: int) -> tuple[int, int, list[str], list[str]]: ...
    def create_note(
        self,
        notetype_id: int,
        deck_id: int,
        fields: list[str],
        tags: list[str],
        on_duplicate: str = "error",
    ) -> int | None: ...
    def update_note(
        self, note_id: int, fields: list[str], tags: list[str] | None = None
    ) -> None: ...
    def delete_notes(self, note_ids: list[int]) -> int: ...

@final
class DerivedTextEngine:
    def __new__(cls, path: str, schema_version: int) -> DerivedTextEngine: ...
    def close(self) -> None: ...
    def get_col_mod(self) -> int | None: ...
    def set_col_mod(self, value: int) -> None: ...
    def count(self) -> int: ...
    def ingest(self, note_id: int, source: str, refs_text: list[tuple[str, str]]) -> None: ...
    def remove(self, note_ids: list[int], source: str | None = None) -> None: ...
    def build(self, rows: list[tuple[int, str, str, str]], col_mod: int) -> None: ...
    def match_rows(
        self, expr: str, limit: int, with_text: bool
    ) -> list[tuple[int, str, str, str | None, str | None]]: ...
